# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 759e5d31c09519bede9eafbd0caa09abe3e1eb843d6ca5f9bb2bdcac9005c68f89f2809ac323a2ad49013258a71c8fd4035715507f74bd5ba004aacb89237a19

test:
  secret_key_base: 4410c3eeb2804fea4646619884a7a964855568db1b1b273fd6b73a6bcb55ad9d8ba480f53f93f65b693fa4f8f78c51020393d11e225c5404e6107e10468fd6f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
